### ISSUE TITLE
redirect http to https

### ISSUE THREAD

**Issue by borodadada** [patrickpissurno/fastify-vhost#2]
Hello, how i can create redirect http to https?
```
fastifyHttp.register(vhost, {
    upstream: 'https://site.com',
    host: 'site.com'
})
```

fastifyHttp = port 80

This not work.

**Comment by patrickpissurno** [comment]
Hi. Thanks for reaching out!

What was the intended behavior?

1. The user opens up the browser, navigates to http://site.com and then is redirected to https://site.com (the url in the address bar changes from http:// to https://)

2. The user opens up the browser, navigates to http://site.com and the website loads up as if it was https://site.com (the url is kept the same, http://site.com, in the address bar, as the request is proxied from http:// to https://)

If it is #1, then fastify-vhost won’t be of any help. You might consider just creating a * route in your http fastify instance and return a reply.redirect to the requested url, but string replacing http for https.

If it is #2 let me know as it is a supported use case and should be working.

Thanks!

**Comment by patrickpissurno** [comment]
If you need any further assistance, please comment and I'll reopen the issue.
